version: '3'

services:
  app:
    build: .
    ports: 
      - 4000:4000
    volumes:
      - .:/home/node/app

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: keymaster

